import os
import pytest
import asyncio
from pathlib import Path
from dotenv import load_dotenv

# Ensure environment variables are loaded
load_dotenv()

from services.tts import generate_tts
from services.stt import transcribe_audio
from services.agent import reply, greet, reset

def test_tts_generation():
    """Test that TTS successfully generates an MP3 file that is not empty."""
    text = "Hello, this is a test message to verify text to speech."
    path = asyncio.run(generate_tts(text))
    
    assert path.exists()
    assert path.suffix == ".mp3"
    assert path.stat().st_size > 0

def test_agent_conversation():
    """Test LangGraph agent greeting, reply and memory behavior."""
    chat_id = 99999
    reset(chat_id)
    
    # Check greeting
    greeting = greet(chat_id)
    assert greeting
    assert isinstance(greeting, str)
    
    # Check simple response
    user_text = "I like playing football."
    bot_reply = reply(chat_id, user_text)
    assert bot_reply
    assert "?" in bot_reply  # System prompt asks to end with a question
    
    # Check memory persistence
    memory_reply = reply(chat_id, "What do I like playing?")
    assert "football" in memory_reply.lower() or "sport" in memory_reply.lower() or "hobby" in memory_reply.lower() or "play" in memory_reply.lower()

def test_stt_transcription_roundtrip():
    """Test Speech-To-Text by transcribing an audio file generated by TTS."""
    # Skip if GROQ API key is missing
    if not os.getenv("GROQ_API_KEY"):
        pytest.skip("GROQ_API_KEY not configured")
        
    original_text = "My name is John"
    audio_path = asyncio.run(generate_tts(original_text))
    
    transcribed_text = transcribe_audio(audio_path)
    assert transcribed_text
    assert "john" in transcribed_text.lower() or "name" in transcribed_text.lower()
