"""
test_vector_translator.py — Compare different translation settings without voice.

Loads training texts (generated by scripts/generate_training_texts.py) and runs
the vector_translator on each text under several configurations, measuring:

  - semantic_similarity: cosine similarity between the original and the
    simplified text in the embedding space (a proxy for meaning preservation)
  - coverage: fraction of original tokens that have a known-vocab candidate
  - length_ratio: |simplified| / |original| (closer to 1.0 = less shrinkage)
  - latency: seconds per text

The best configuration is reported at the end.

Groq has a daily token limit per model. The default model
`llama-3.1-8b-instant` has 500k TPD (vs 100k for the 70b model), which is
usually enough for full grid runs.
"""
import argparse
import json
import logging
import os
import statistics
import sys
import time
from itertools import product
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

from services.embeddings import initialize, active_backend, active_dim, embed
from services.vector_vocabulary import (
    VectorVocabulary,
    get_vector_vocabulary,
    _WORD_RE,
)
from services.vector_translator import (
    TranslationConfig,
    select_relevant_vocabulary,
    build_prompt,
    BASIC_WORDS,
)

log = logging.getLogger("test_vector_translator")

DEFAULT_MODEL = os.getenv("GROQ_TEST_MODEL", "llama-3.1-8b-instant")


def translate_with_retry(
    text: str,
    cfg: TranslationConfig,
    vocab: VectorVocabulary,
    model_name: str,
    max_retries: int = 3,
) -> str | None:
    """Translate with exponential backoff on rate-limit errors."""
    selected = select_relevant_vocabulary(text, vocab, cfg)
    system_prompt, user_prompt = build_prompt(text, selected, cfg)
    llm = ChatGroq(
        model=model_name,
        temperature=cfg.temperature,
        max_tokens=cfg.max_tokens,
        groq_api_key=os.getenv("GROQ_API_KEY"),
    )
    for attempt in range(max_retries):
        try:
            response = llm.invoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_prompt),
            ])
            return response.content.strip()
        except Exception as e:
            err = str(e)
            if "429" in err or "rate_limit" in err.lower():
                wait = 5 * (2 ** attempt)
                log.warning("Rate limit, waiting %ds (attempt %d)", wait, attempt + 1)
                time.sleep(wait)
            else:
                log.warning("Translate error: %s", e)
                return None
    log.warning("All retries exhausted for: %s", text[:50])
    return None


def measure_semantic_similarity(
    original: str,
    simplified: str,
) -> float:
    """Cosine similarity between embeddings of the two texts."""
    if not simplified.strip():
        return 0.0
    a = embed(original, use_cache=True)
    b = embed(simplified, use_cache=True)
    na = np.linalg.norm(a) + 1e-10
    nb = np.linalg.norm(b) + 1e-10
    return float((a @ b) / (na * nb))


def measure_coverage(
    original: str,
    vocab: VectorVocabulary,
) -> float:
    """Fraction of unique original tokens that have a known-vocab candidate
    above the default threshold (0.0 here = any candidate).
    """
    tokens = list({t.lower() for t in _WORD_RE.findall(original)})
    if not tokens:
        return 1.0
    known = vocab.tokens()
    known_in = sum(1 for t in tokens if t in known)
    unknown = [t for t in tokens if t not in known]
    if not unknown:
        return 1.0
    sims = vocab.find_similar_batch(unknown, top_k=1, threshold=0.0)
    with_candidate = sum(1 for w, hits in sims.items() if hits)
    return (known_in + with_candidate) / len(tokens)


def measure_length_ratio(original: str, simplified: str) -> float:
    if not original.strip():
        return 0.0
    return len(simplified) / max(1, len(original))


def run_one_config(
    cfg: TranslationConfig,
    texts: list[dict],
    vocab: VectorVocabulary,
    model_name: str = DEFAULT_MODEL,
) -> dict:
    """Run vector_translate on all texts with the given config; aggregate metrics."""
    sem_scores: list[float] = []
    cover_scores: list[float] = []
    length_ratios: list[float] = []
    latencies: list[float] = []

    for t in texts:
        text = t["text"]
        try:
            t0 = time.perf_counter()
            simplified = translate_with_retry(text, cfg, vocab, model_name)
            elapsed = time.perf_counter() - t0
        except Exception as e:
            log.warning("Translate failed: %s", e)
            continue
        if not simplified:
            continue

        sem = measure_semantic_similarity(text, simplified)
        cov = measure_coverage(text, vocab)
        lr = measure_length_ratio(text, simplified)

        sem_scores.append(sem)
        cover_scores.append(cov)
        length_ratios.append(lr)
        latencies.append(elapsed)
        log.info("  cfg temp=%.2f top_k=%d max=%d thr=%.2f | sem=%.3f cov=%.2f lr=%.2f | %s -> %s",
                 cfg.temperature, cfg.top_k_per_word, cfg.max_vocab_in_prompt,
                 cfg.similarity_threshold, sem, cov, lr,
                 text[:50], simplified[:50])

    if not sem_scores:
        return {
            "config": cfg.__dict__,
            "n": 0,
            "sem_mean": 0.0,
            "cov_mean": 0.0,
            "lr_mean": 0.0,
            "latency_mean": 0.0,
            "score": 0.0,
        }
    sem_mean = statistics.mean(sem_scores)
    cov_mean = statistics.mean(cover_scores)
    lr_mean = statistics.mean(length_ratios)
    lat_mean = statistics.mean(latencies)

    # Composite score: prioritize semantic similarity (meaning preservation),
    # then coverage, then length stability, penalize long latency.
    score = (
        0.65 * sem_mean
        + 0.20 * cov_mean
        + 0.10 * max(0.0, 1.0 - abs(1.0 - lr_mean))
        - 0.05 * min(1.0, lat_mean / 5.0)
    )

    return {
        "config": cfg.__dict__,
        "n": len(sem_scores),
        "sem_mean": sem_mean,
        "cov_mean": cov_mean,
        "lr_mean": lr_mean,
        "latency_mean": lat_mean,
        "score": score,
    }


def iter_configs(grid: dict) -> Iterable[TranslationConfig]:
    keys = list(grid.keys())
    for combo in product(*[grid[k] for k in keys]):
        yield TranslationConfig(**dict(zip(keys, combo)))


def print_results(results: list[dict]) -> None:
    print("\n" + "=" * 100)
    print(f"{'rank':<5}{'temp':<7}{'top_k':<7}{'max_v':<7}{'thr':<7}{'sem':<8}{'cov':<8}{'lr':<7}{'lat':<7}{'score':<8}")
    print("-" * 100)
    sorted_r = sorted(results, key=lambda r: -r["score"])
    for rank, r in enumerate(sorted_r, start=1):
        c = r["config"]
        marker = " <-- BEST" if rank == 1 else ""
        print(f"{rank:<5}{c['temperature']:<7.2f}{c['top_k_per_word']:<7}{c['max_vocab_in_prompt']:<7}"
              f"{c['similarity_threshold']:<7.2f}{r['sem_mean']:<8.3f}{r['cov_mean']:<8.3f}"
              f"{r['lr_mean']:<7.2f}{r['latency_mean']:<7.2f}{r['score']:<8.3f}{marker}")
    print("=" * 100)  # type: ignore[name-defined]
    best = sorted_r[0]
    print(f"\nBEST CONFIG:")
    for k, v in best["config"].items():
        print(f"  {k}: {v}")
    print(f"  semantic_similarity: {best['sem_mean']:.3f}")
    print(f"  coverage: {best['cov_mean']:.3f}")
    print(f"  length_ratio: {best['lr_mean']:.2f}")
    print(f"  latency: {best['latency_mean']:.2f}s")
    print(f"  composite_score: {best['score']:.3f}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--texts", default="results/training_texts.json")
    ap.add_argument("--limit", type=int, default=0,
                    help="Use only first N texts (0 = all)")
    ap.add_argument("--output", default="results/vector_translator_comparison.json")
    ap.add_argument("--quick", action="store_true",
                    help="Run a smaller grid for fast smoke-testing")
    ap.add_argument("--full", action="store_true",
                    help="Run the full grid (default grid otherwise)")
    ap.add_argument("--temps", default=None,
                    help="Comma-separated list, e.g. 0.1,0.3")
    ap.add_argument("--topks", default=None)
    ap.add_argument("--maxvs", default=None)
    ap.add_argument("--thrs", default=None)
    ap.add_argument("--model", default=DEFAULT_MODEL,
                    help=f"Groq model to use (default: {DEFAULT_MODEL})")
    ap.add_argument("--resume", action="store_true",
                    help="Skip configs already present in the output JSON")
    args = ap.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    load_dotenv(ROOT / ".env")
    if not os.getenv("GROQ_API_KEY"):
        print("ERROR: GROQ_API_KEY is not set", file=sys.stderr)
        return 1

    backend, dim = initialize()
    print(f"Embedding backend: {backend}, dim={dim}")

    print("Loading vocabulary + vectors...")
    vocab = get_vector_vocabulary("en")
    vocab.load()
    print(f"  loaded {len(vocab)} words")

    texts_path = ROOT / args.texts
    if not texts_path.exists():
        print(f"ERROR: {texts_path} not found. Run generate_training_texts.py first.",
              file=sys.stderr)
        return 1
    with open(texts_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    texts = data["texts"]
    if args.limit:
        texts = texts[: args.limit]
    print(f"Loaded {len(texts)} training texts from {texts_path}")

    def _floats(s, default):
        if s is None:
            return default
        return [float(x) for x in s.split(",")]

    def _ints(s, default):
        if s is None:
            return default
        return [int(x) for x in s.split(",")]

    if args.quick:
        grid = {
            "temperature": [0.2, 0.4],
            "top_k_per_word": [5, 10],
            "max_vocab_in_prompt": [120, 200],
            "similarity_threshold": [0.45],
        }
    elif args.full:
        grid = {
            "temperature": [0.1, 0.2, 0.3, 0.5],
            "top_k_per_word": [5, 8, 12],
            "max_vocab_in_prompt": [60, 120, 250],
            "similarity_threshold": [0.35, 0.45, 0.55],
        }
    else:
        grid = {
            "temperature": _floats(args.temps, [0.1, 0.2, 0.3, 0.5]),
            "top_k_per_word": _ints(args.topks, [5, 8, 12]),
            "max_vocab_in_prompt": _ints(args.maxvs, [60, 120, 250]),
            "similarity_threshold": _floats(args.thrs, [0.35, 0.45, 0.55]),
        }
    configs = list(iter_configs(grid))
    total_calls = len(configs) * len(texts)
    print(f"Total configs to test: {len(configs)} x {len(texts)} texts = "
          f"{total_calls} LLM calls")
    if total_calls > 200:
        print("WARNING: > 200 LLM calls, this may take 5+ minutes")
    print()

    out_path = ROOT / args.output
    out_path.parent.mkdir(parents=True, exist_ok=True)

    results: list[dict] = []
    completed_keys: set[tuple] = set()

    if args.resume and out_path.exists():
        try:
            with open(out_path, "r", encoding="utf-8") as f:
                prev = json.load(f)
            for r in prev.get("results", []):
                c = r.get("config", {})
                key = (
                    round(float(c.get("temperature", 0)), 4),
                    int(c.get("top_k_per_word", 0)),
                    int(c.get("max_vocab_in_prompt", 0)),
                    round(float(c.get("similarity_threshold", 0)), 4),
                )
                if r.get("n", 0) > 0:
                    results.append(r)
                    completed_keys.add(key)
            print(f"Resuming: {len(completed_keys)} configs already done")
        except Exception as e:
            print(f"Could not resume: {e}")

    for i, cfg in enumerate(configs, start=1):
        key = (
            round(cfg.temperature, 4),
            cfg.top_k_per_word,
            cfg.max_vocab_in_prompt,
            round(cfg.similarity_threshold, 4),
        )
        if key in completed_keys:
            log.info("Config %d/%d: SKIP (already done) %s", i, len(configs), cfg.__dict__)
            continue
        log.info("Config %d/%d: %s", i, len(configs), cfg.__dict__)
        r = run_one_config(cfg, texts, vocab, model_name=args.model)
        results.append(r)
        completed_keys.add(key)
        # Save incrementally so partial results are not lost
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump({
                "embedding_backend": backend,
                "embedding_dim": dim,
                "vocab_size": len(vocab),
                "n_texts": len(texts),
                "n_configs": len(configs),
                "completed_configs": len(completed_keys),
                "model": args.model,
                "results": results,
            }, f, ensure_ascii=False, indent=2)

    print_results(results)

    print(f"\nDetailed results saved to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
